require 'dm-core/property/legacy/html_text'
require 'dm-core/property/legacy/uri_text'
require 'dm-core/property/legacy/time_string'
require 'dm-core/property/legacy/date_string'
require 'dm-core/property/legacy/numeric_ip_addr'
